### ISSUE TITLE
Ethminer not finding any solution or submitting any shares

### ISSUE THREAD

**Issue by GigaDroid** [ethereum/webthree-umbrella#361]
Running R9 380 on Windows 10 and 16.3 drivers never finds any solution.
Same setup is working on Linux just fine.

**Comment by smartbitcoin** [comment]
if you are not on a pool mining,  base on current difficulty, it wont find anything for a long time ( few days).

**Comment by GigaDroid** [comment]
Forgot to mention I'm pool mining.
Also tried many different pools.

**Comment by billprescott** [comment]
I am having the same issue.  Appears to mine but never finds a solution. Inhave also tried on many pools. Using Windows.  Have been mining since Frontier started. This appears to be a new issue.

**Comment by billprescott** [comment]
Forgot to mention. AMD Radeon R9 Fury X

**Comment by chriseth** [comment]
Do you have any logs? Do you use ethminer together with geth?

**Comment by billprescott** [comment]
![image](https://cloud.githubusercontent.com/assets/13895845/13889235/8d61b36c-ed99-11e5-8c95-f35f7d728924.png)
Attached is the log file while pool mining.  It looks ok except that it never finds a solution and submits. The pool does not see the miner even though it look like its mining.  Have tried three pools. Solo mining gets the Worker error.  

Let me know what other logs you need. 

Thanks

Bill

![image](https://cloud.githubusercontent.com/assets/13895845/13889325/1b99834e-ed9a-11e5-8c1c-1f0f9530c6a2.png)

**Comment by TheDeafMute** [comment]
Having same issue on a new rig. Its my only rig using an r7 360 nitro around 4.5mh. I thought it was a connection issue (like duplicate worker name/host name etc) but it's not. Just keeps hashing and burning heat and electricity on its merry way into burning itself into oblivion.. but doesn't generate eth for doing so, or "find shares" on any pool I've tried. Is the low hashrate too low?? Hours at 4.5MH no shares no visibility on pool...

**Comment by bobsummerwill** [comment]
Answered on the new issue you logged, @TheDeafMute, but will echo it here too for the other people following this ...

Have you tried the Genoil ethminer? If not, you probably should. It's had a lot more love that the official ethminer. We hope to upstream their changes back, but for right now they have a better miner.

http://github.com/Genoil/cpp-ethereum

**Comment by scmike** [comment]
I just got this EXACT problem resolved with lots of amazing help from Alex at Ethereum nanopool (http://eth.nanopool.org/help). I purchased two Gigabyte R9 380x G1 cards yesterday and installed them to replace a 7870. After installing and updating drivers to 16.3, my pool mining no longer worked. 

The solution is to download and install the AMD 15.12 driver. I did an uninstall of 16.3, ran CCleaner to cleanup leftover reg entries, restarted, and then installed 15.12. I ran my same batch files and within a few minutes I was submitting shares and my account was visible on the pool again.

I tried everything I could before this, like different pools, stratum vs getwork, and nothing made any difference. The logs all looked great (except never submitting shares). The AMD driver is absolutely the issue. 

Lastly - I had trouble finding a 15.12 driver that was not a web installer (which connects and installs 16.3). I ended up using this one (it's safe) http://www.guru3d.com/files-get/amd-radeon-software-crimson-15-12-driver-download,2.html

Again, big thanks to Alex at Ethereum nanopool, and please send some hashrate their way if this helped solve your issues.

**Comment by stephenstroud** [comment]
This is also happening to me, I've tried with Genoil but no luck, I will try with the 15.12 driver. Did anyone have any luck fixing this please?

Windows 10 
Etherminer + geth

**Comment by stephenstroud** [comment]
Downgrading my driver to 15.12 didn't solve it for me straight away, but after running ccleaner it's kicked into life. @scmike  Thank you! I can finally begin mining for the first time. 👍

**Comment by bobsummerwill** [comment]
Good to hear, @stephenstroud.
GPU mining appears to be very sensitive to driver support.    Glad you found a workaround.

**Comment by pmartiamarista** [comment]
When you install gpu drivers i recomend to use Display Driver Uninstaller(DDU) http://www.guru3d.com/files-details/display-driver-uninstaller-download.html

**Comment by SystemOfSilence** [comment]
This can probably be closed. It is fixed in the current release. There is still driver craziness (AMD users stay at 15.12) but is a separate issue from ethminer not submitting work.

**Comment by bobsummerwill** [comment]
Thanks, @SilentSystem.

**Comment by sanblch** [comment]
I have the same problem. Binaries work perfect: claimore, qtminer. Built from source ones cannot find solution and don't submit shares. Neither webthree-umbrella/ethminer nor qtminer nor genoil/ethminer. I have Ubuntu 15.10 and have already tried both official web site 15.12 drivers, and fglrx-updates from rep.

**Comment by bootsiaz** [comment]
I have the same issue but is unresolved. Had a worker running for 4 months solid with r9 290 and 390 with 15.12 drivers. I got a rx 470 and installed 16.9.2 drivers (the 390 lost 30% hash rate). Now in that state where it mines but never finds a solution. Uninstalled, ran ccleaner, installed 15.12 again, removed amd folders, deleted dag many times, still stuck in that state. One weird thing is the 390 still has a lower hash rate. Any ideas are appreciated.

**Comment by bobsummerwill** [comment]
Hey @bootsiaz,

Head to https://gitter.im/ethereum/minercommunitysupport for help.

**Comment by bootsiaz** [comment]
Will do, thanks.

**Comment by stephenstroud** [comment]
@bobsummerwill I commented above a while ago regarding this issue and had to downgrade my Crimson driver to 15.12 to get successful mining submits, I recently upgraded my crimson driver to 16.11, however, again this problem persists with the latest driver. The console screens shows mining without errors until I don't see stats being recorded with the mining pool. I'm running on Windows 10, other people I know are experience the same issues with the later drivers on Windows. Perhaps the drivers aren't compatible with the miner. Do you have any ideas how I could resolve this please?

**Comment by stephenstroud** [comment]
Also the hash rate appears lower when running with drivers greater than 16.

**Comment by movitto** [comment]
Had anyone encourntered this issue w/ a nvidia card on linux? I see the solutions here are to downgrade the ATI driver, but no mention of nvidia.

I'm running into the same issue w/ my nvidia 1080ti. Official nvidia drivers for linux we successfully installed, and I can see that I'm getting the target hashrate for my card ~30MH/s. While it can successfully connect to  and get work from nanopool, dwarfpool, ethereumpool, and others, no shares are submitted. It just continuously tries to compute the latest job received until the next job is received,

Command:

```
export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
~/cpp-ethereum/build/ethminer/ethminer --farm-recheck 200 -G -S eth-us-east1.nanopool.org:9999 -O [RETRACTED]
```


example output (addresses have been changed to protect the innocent):

```
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_ 

Please consider a donation to:
ETH: [RETRACTED]
[OPENCL]:Found suitable OpenCL device [GeForce GTX 1080 Ti] with 11715084288 bytes of GPU memory
  ℹ  11:36:37|ethminer  Connecting to stratum server eth-us-east1.nanopool.org:9999
  ℹ  11:36:38|stratum  Connected to stratum server eth-us-east1.nanopool.org : 9999
  ℹ  11:36:38|stratum  Starting farm
  ℹ  11:36:38|stratum  Subscribed to stratum server
  ℹ  11:36:38|stratum  Authorized worker [RETRACTED]
  ℹ  11:36:38|stratum  Received new job #f55c54da
  ℹ  11:36:38|openclminer0  set work; seed: #647f6619, target:  #00000000dbe6
  ℹ  11:36:38|openclminer0  Initialising miner...
  m  11:36:38|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
[More similar output]

[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 1080 Ti(OpenCL 1.2 CUDA)
  m  11:36:40|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
[OPENCL]:Generating DAG data
OPENCL#0: 0%
  m  11:36:40|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
OPENCL#0: 1%
OPENCL#0: 2%
OPENCL#0: 2%
  m  11:36:41|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
OPENCL#0: 3%
OPENCL#0: 4%
OPENCL#0: 5%
[More similar output]
OPENCL#0: 97%
  m  11:36:49|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
OPENCL#0: 98%
OPENCL#0: 98%
OPENCL#0: 99%
  m  11:36:49|ethminer  Mining on PoWhash #f55c54da : 10.49MH/s [A0+0:R0+0:F0]
  m  11:36:50|ethminer  Mining on PoWhash #f55c54da : 31.46MH/s [A0+0:R0+0:F0]
  [More similar output]
  ℹ  11:36:56|stratum  Received new job #8cdc1d7d
  ℹ  11:36:56|openclminer0  set work; seed: #647f6619, target:  #00000000dbe6
[Ad inf until I kill the process]
```


I have attempted this over the course of a few days to make sure there are not network issues (the main geth client has been syncing the blockchain fine in that time).

Does anyone have an ideas? Is there an easy way to debug exactly whats going on (if the card isn't actually computing the hashes, if they aren't being sent to the sever, if the server isn't accepting them)

Thanks for any help

**Comment by aydinhus** [comment]
I'm having trouble too. Ubuntu 16.04, Nvidia p100, cuda 8.0, genoil working properly but no shares are submited.

**Comment by reppolice** [comment]
Having the same problem on GTX 1070 Windows Server 2016, nanopool has not seen a share from me in 30 minutes of running the genoil binary, but still the nanopool "counter" kept increasing in those 30 minutes, no idea how to interpret these facts. The clay dual miner instead immediately gives ETH shares, achieving half of the genoil rate. Strangely the nanopool graph that shows shares as well has recorded some shares, while the HTML table below was showing 0 shares.

**Comment by ketetefid** [comment]
Oh..I'm not alone! I was wondering what is wrong with my setup and it seems that the miner has some problems. I really had no clue...
GTX 1070 on Gentoo Linux, latest drivers, hashing like a charm but producing not even a cent. It hashes well apparently but nothing appears on the pool stats. Does anyone have a remedy for this? Please tell us a workaround.
I built the miner from the source.

**Comment by bobsummerwill** [comment]
You probably want to head to https://github.com/ethereum-mining/ethminer, guys.

This repo has been inactive for a year.

**Comment by ketetefid** [comment]
Thank you bobsummerwill. I will take the advice and see if it changes anything.

**Comment by progone** [comment]
@ketetefid I use Ubuntu 16.04,  I found a solution in the Nvidia setting,  this video gave me enough hints to open the nvidia setting via terminal.  The video is based on Windows thou.... but Nvidia hierarchy is the same for both systems.  Good luck [Nvidia Settings](https://youtu.be/hCriJL07zic)

**Comment by YanBellavance** [comment]
This happens to me when I modify the code and made a mistake. The problem is that the exit condition for work gets overlooked somehow, perhaps skipped or there a conflict somewhere with the threads or the index into data lost its  sense of direction
