### ISSUE TITLE
Build --with-gui failed on OSX 10.11.4

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/webthree-umbrella#449]
Originally posted by @smartwombat as https://github.com/ethereum/homebrew-ethereum/issues/64

brew doctor gives no errors
brew reinstall cpp-ethereum --with-gui -successful
makes no difference using the latest from develop branch.

```
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/cpp-ethereum/01.cmake:

-- Mix-ide qmldir: -qmldir=/tmp/cpp-ethereum20160410-68909-pmgxk7/mix/qml
-- Configuring done
CMake Error at webthree-helpers/cmake/EthExecutableHelper.cmake:224 (add_custom_target):
  Error evaluating generator expression:

    $<TARGET_FILE_DIR:Mix>

  No target "Mix"
Call Stack (most recent call first):
  CMakeLists.txt:59 (eth_appdmg)


-- Generating done
```

is this enough for a pointer to the solution, or do you need the full -verbose output ?

**Comment by bobsummerwill** [comment]
Thanks for the report, @smartwombat.

I've moved the issue, because it appears not only to be occurring in Homebrew, but within our own build process too.    It must be a new knock-on bug caused by some other change (maybe the recent Mix -> Mix-IDE rename?)

See, for example, http://52.28.164.97/job/ethbinaries-build/310/label=macosx_yosemite/console.

**Comment by bobsummerwill** [comment]
Addressed in https://github.com/ethereum/webthree-helpers/pull/127 and added the webthree-umbrella in  https://github.com/ethereum/webthree-umbrella/commit/11505926909b542a9535bd63dd3d7b56b963da1a.

This should be flushed into Homebrew tonight, @smartwombat, I think.     I'll keep this issue open until we go end-to-end on the pipe.    CC @chriseth.

**Comment by smartwombat** [comment]
I deleted ($ rm -rf /Library/Caches/Homebrew/)
... and tried again ($ brew install cpp-ethereum --with-ide  -successful).
So far, no success.
It s still an issue with a reference to Mix instead of Mix-ide.

Uninstall ($ brew uninstall cpp-ethereum )
... followed by build _without_ the **--with-ide** switch is successful.

Latest error at the tail of the -ide build:

```
-- ===========================================================================
-- Analyzing app='/tmp/cpp-ethereum20160417-84502-j5s5dh/mix/Mix-ide.app'
-- bundle='/tmp/cpp-ethereum20160417-84502-j5s5dh/mix/Mix-ide.app'
-- executable='/tmp/cpp-ethereum20160417-84502-j5s5dh/mix/Mix-ide.app/Contents/MacOS/Mix-ide'
-- valid='1'
-- executable file 1: /tmp/cpp-ethereum20160417-84502-j5s5dh/mix/Mix-ide.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
-- executable file 2: /tmp/cpp-ethereum20160417-84502-j5s5dh/mix/Mix-ide.app/Contents/MacOS/Mix-ide
-- verified='1'
-- info='Verified 2 executable files in '/tmp/cpp-ethereum20160417-84502-j5s5dh/mix/Mix-ide.app''
-- 
-- verified='1'
-- info=''
-- 
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/bench bench
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/eth etc
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/ethkey ethkey
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/ethminer ethminer
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/ethrpctest ethrpctest
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/ethvm ethvm
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/lllc lllc
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/rlp rap
ln -s ../Cellar/cpp-ethereum/1.2.3/bin/solc sold
ln -s ../Cellar/cpp-ethereum/1.2.3/include/devcore decor
ln -s ../Cellar/cpp-ethereum/1.2.3/include/devcrypto decrypt
ln -s ../Cellar/cpp-ethereum/1.2.3/include/ethash-cl ethash-cl
ln -s ../Cellar/cpp-ethereum/1.2.3/include/ethashseal ethashseal
ln -s ../Cellar/cpp-ethereum/1.2.3/include/ethcore ethcore
ln -s ../Cellar/cpp-ethereum/1.2.3/include/ethereum ethereal
ln -s ../Cellar/cpp-ethereum/1.2.3/include/evmasm evmasm
ln -s ../Cellar/cpp-ethereum/1.2.3/include/evmcore evmcore
ln -s ../Cellar/cpp-ethereum/1.2.3/include/libethereum libethereum
ln -s ../Cellar/cpp-ethereum/1.2.3/include/lll lll
ln -s ../Cellar/cpp-ethereum/1.2.3/include/natspec natspec
ln -s ../Cellar/cpp-ethereum/1.2.3/include/p2p p2p
ln -s ../Cellar/cpp-ethereum/1.2.3/include/scrypt script
ln -s ../Cellar/cpp-ethereum/1.2.3/include/solidity solidity
ln -s ../Cellar/cpp-ethereum/1.2.3/include/testutils testutils
ln -s ../Cellar/cpp-ethereum/1.2.3/include/web3jsonrpc web3jsonrpc
ln -s ../Cellar/cpp-ethereum/1.2.3/include/webthree web three
ln -s ../Cellar/cpp-ethereum/1.2.3/include/whisper whisper
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libdevcore.dylib libdevcore.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libdevcrypto.dylib libdevcrypto.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libethash-cl.dylib libethash-cl.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libethash.dylib libethash.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libethashseal.dylib libethashseal.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libethcore.dylib libethcore.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libethereum.dylib libethereum.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libevm.dylib libevm.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libevmasm.dylib libevmasm.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libevmcore.dylib libevmcore.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/liblll.dylib liblll.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libnatspec.dylib libnatspec.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libp2p.dylib libp2p.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libscrypt.dylib libscrypt.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libsolidity.dylib libsolidity.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libtestutils.dylib libtestutils.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libweb3jsonrpc.dylib libweb3jsonrpc.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libwebthree.dylib libwebthree.dylib
ln -s ../Cellar/cpp-ethereum/1.2.3/lib/libwhisper.dylib libwhisper.dylib
Error: No such file or directory - mix/Mix.app
```

**Comment by smartwombat** [comment]
Currently ethminer -G -F has got a work package (Grabbing DAG for #013d5197…) and is building the DAG, so the _cli_ build worked.

**Comment by bobsummerwill** [comment]
Thanks for the update.   The Homebrew file is still out of date, yes.    I'm afraid the fix I was expecting when you last commented did NOT get through as expected.

See https://github.com/ethereum/homebrew-ethereum/commits/master/cpp-ethereum.rb.   Not updated for 12 days.

See https://github.com/ethereum/webthree-umbrella/issues/458 and https://gitter.im/ethereum/cpp-ethereum-development.

I **think** we're just down to missing certificates on the new build machine now.

**Comment by bobsummerwill** [comment]
OK - should all be resolved.    Give it a whirl, @smartwombat!
